from pydantic import BaseModel, Field
from typing import List, Optional
from enum import Enum


class MsgType(str, Enum):
    PROPOSE   = "PROPOSE"
    COUNTER   = "COUNTER"
    ACCEPT    = "ACCEPT"
    REJECT    = "REJECT"
    WALK_AWAY = "WALK_AWAY"


class DealTerms(BaseModel):
    unit_price:     float
    quantity:       int
    delivery_date:  str   # ISO 8601: "2026-08-30"
    payment_terms:  str   # e.g. "Net-60"
    warranty_years: int


class Citation(BaseModel):
    source:         str             # filename or URL
    section:        Optional[str]  = None
    retrieved_date: Optional[str]  = None  # required for web citations


class MessageEnvelope(BaseModel):
    agent_id:      str
    msg_type:      MsgType
    payload:       DealTerms
    rationale:     str
    citations:     List[Citation]
    turn:          int
    input_tokens:  int = Field(default=0)   # tokens consumed by this turn's API call
    output_tokens: int = Field(default=0)   # tokens generated by this turn's API call